/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthredirRouteRouteImport } from './routes/auth/(redir)/route'
import { Route as AppSettingsRouteRouteImport } from './routes/app/settings/route'
import { Route as AppsidebarRouteRouteImport } from './routes/app/(sidebar)/route'
import { Route as AppsidebarIndexRouteImport } from './routes/app/(sidebar)/index'
import { Route as AuthredirSignupRouteImport } from './routes/auth/(redir)/signup'
import { Route as AuthredirSigninRouteImport } from './routes/auth/(redir)/signin'
import { Route as AuthpostOrganizationRouteImport } from './routes/auth/(post)/organization'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as AppSettingsPreferencesRouteImport } from './routes/app/settings/preferences'
import { Route as AppSettingsOrganizationRouteImport } from './routes/app/settings/organization'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthredirRouteRoute = AuthredirRouteRouteImport.update({
  id: '/auth/(redir)',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppsidebarRouteRoute = AppsidebarRouteRouteImport.update({
  id: '/(sidebar)',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppsidebarIndexRoute = AppsidebarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsidebarRouteRoute,
} as any)
const AuthredirSignupRoute = AuthredirSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthredirRouteRoute,
} as any)
const AuthredirSigninRoute = AuthredirSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthredirRouteRoute,
} as any)
const AuthpostOrganizationRoute = AuthpostOrganizationRouteImport.update({
  id: '/auth/(post)/organization',
  path: '/auth/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsPreferencesRoute = AppSettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppsidebarRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/auth': typeof AuthredirRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/organization': typeof AppSettingsOrganizationRoute
  '/app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/auth/organization': typeof AuthpostOrganizationRoute
  '/auth/signin': typeof AuthredirSigninRoute
  '/auth/signup': typeof AuthredirSignupRoute
  '/app/': typeof AppsidebarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppsidebarIndexRoute
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/auth': typeof AuthredirRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/organization': typeof AppSettingsOrganizationRoute
  '/app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/auth/organization': typeof AuthpostOrganizationRoute
  '/auth/signin': typeof AuthredirSigninRoute
  '/auth/signup': typeof AuthredirSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/(sidebar)': typeof AppsidebarRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/auth/(redir)': typeof AuthredirRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/settings/organization': typeof AppSettingsOrganizationRoute
  '/app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/auth/(post)/organization': typeof AuthpostOrganizationRoute
  '/auth/(redir)/signin': typeof AuthredirSigninRoute
  '/auth/(redir)/signup': typeof AuthredirSignupRoute
  '/app/(sidebar)/': typeof AppsidebarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/settings'
    | '/auth'
    | '/api/auth/$'
    | '/app/settings/organization'
    | '/app/settings/preferences'
    | '/app/settings/profile'
    | '/auth/organization'
    | '/auth/signin'
    | '/auth/signup'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/settings'
    | '/auth'
    | '/api/auth/$'
    | '/app/settings/organization'
    | '/app/settings/preferences'
    | '/app/settings/profile'
    | '/auth/organization'
    | '/auth/signin'
    | '/auth/signup'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/(sidebar)'
    | '/app/settings'
    | '/auth/(redir)'
    | '/api/auth/$'
    | '/app/settings/organization'
    | '/app/settings/preferences'
    | '/app/settings/profile'
    | '/auth/(post)/organization'
    | '/auth/(redir)/signin'
    | '/auth/(redir)/signup'
    | '/app/(sidebar)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthredirRouteRoute: typeof AuthredirRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthpostOrganizationRoute: typeof AuthpostOrganizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/(redir)': {
      id: '/auth/(redir)'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthredirRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(sidebar)': {
      id: '/app/(sidebar)'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppsidebarRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/(sidebar)/': {
      id: '/app/(sidebar)/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppsidebarIndexRouteImport
      parentRoute: typeof AppsidebarRouteRoute
    }
    '/auth/(redir)/signup': {
      id: '/auth/(redir)/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthredirSignupRouteImport
      parentRoute: typeof AuthredirRouteRoute
    }
    '/auth/(redir)/signin': {
      id: '/auth/(redir)/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthredirSigninRouteImport
      parentRoute: typeof AuthredirRouteRoute
    }
    '/auth/(post)/organization': {
      id: '/auth/(post)/organization'
      path: '/auth/organization'
      fullPath: '/auth/organization'
      preLoaderRoute: typeof AuthpostOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/preferences': {
      id: '/app/settings/preferences'
      path: '/preferences'
      fullPath: '/app/settings/preferences'
      preLoaderRoute: typeof AppSettingsPreferencesRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/organization': {
      id: '/app/settings/organization'
      path: '/organization'
      fullPath: '/app/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppsidebarRouteRouteChildren {
  AppsidebarIndexRoute: typeof AppsidebarIndexRoute
}

const AppsidebarRouteRouteChildren: AppsidebarRouteRouteChildren = {
  AppsidebarIndexRoute: AppsidebarIndexRoute,
}

const AppsidebarRouteRouteWithChildren = AppsidebarRouteRoute._addFileChildren(
  AppsidebarRouteRouteChildren,
)

interface AppSettingsRouteRouteChildren {
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
  AppSettingsPreferencesRoute: typeof AppSettingsPreferencesRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
  AppSettingsPreferencesRoute: AppSettingsPreferencesRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppsidebarRouteRoute: typeof AppsidebarRouteRouteWithChildren
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppsidebarRouteRoute: AppsidebarRouteRouteWithChildren,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthredirRouteRouteChildren {
  AuthredirSigninRoute: typeof AuthredirSigninRoute
  AuthredirSignupRoute: typeof AuthredirSignupRoute
}

const AuthredirRouteRouteChildren: AuthredirRouteRouteChildren = {
  AuthredirSigninRoute: AuthredirSigninRoute,
  AuthredirSignupRoute: AuthredirSignupRoute,
}

const AuthredirRouteRouteWithChildren = AuthredirRouteRoute._addFileChildren(
  AuthredirRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthredirRouteRoute: AuthredirRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthpostOrganizationRoute: AuthpostOrganizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
